services:
  frontend:
    build: ./web
    hostname: frontend
    ports:
      - "81:80"
    networks:
      - test-network
  backend:
    build: ./app
    hostname: backend
    ports:
      - "82:3000"
    networks:
      - test-network
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - test-network

volumes:
  mongo-data:
    driver: local
    
networks:
  test-network:
    driver: bridge